### ISSUE TITLE
Training on Nuscenes dataset

### ISSUE THREAD

**Issue by FeiT-FeiTeng** [alexanderswerdlow/BEVGen#9]
Thank you for your outstanding work. I am trying to replicate your work on the Nuscenes dataset, but in the process of using datamodule: stage_1_bev_v2.yaml, I found that it requires a ConcatDataset which needs to import MetadriveDataset. When I choose stage_1_nuscenes.yaml, it calls the get_single_image() function instead.

**Comment by alexanderswerdlow** [comment]
Hi! You can comment out that second dataset [BEVs from Metadrive] and just train on nuScenes as long as you don't plan on using Metadrive generated BEV maps at inference time.

Something like this should work:
```
train:
  - _target_: multi_view_generation.bev_utils.nuscenes_dataset.NuScenesDataset
    split: 0
    return_cam_img: False
    return_bev_img: True
    augment_bev_img: True
    mini_dataset: ${extras.mini_dataset}
    dataset_dir: ${paths.nuscenes_dir}
    metadrive_compatible: False
    metadrive_compatible_v2: True
    only_keyframes: True
```
